language: python

# Run jobs on container-based infrastructure, can be overridden per job
dist: trusty

matrix:
  include:
    # Extra includes for OSX since python language is not available by default on OSX
    - os: osx
      language: generic
      env:
        - PYTHON_VER=3.6
        - ENVIRON=OPENEYE

    - os: osx
      language: generic
      env:
        - PYTHON_VER=3.6
        - ENVIRON=RDKIT

    - os: osx
      language: generic
      env:
        - PYTHON_VER=3.6
        - ENVIRON=CMILES

    - os: linux
      python: 3.6
      env:
        - PYTHON_VER=3.6
        - ENVIRON=OPENEYE

    - os: linux
      python: 3.6
      env:
        - PYTHON_VER=3.6
        - ENVIRON=RDKIT

    - os: linux
      python: 3.6
      env:
        - PYTHON_VER=3.6
        - ENVIRON=CMILES

env:
  global:
    # Location of decrypted OpenEye license file
    - OE_LICENSE="$HOME/oe_license.txt"

before_install:
    # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a

    # Install the Python environment
  - source devtools/travis-ci/before_install.sh
  - python -V
  # Get new encryption
  - if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then  openssl aes-256-cbc -K $encrypted_ef0be1cff144_key -iv $encrypted_ef0be1cff144_iv -in oe_license.txt.enc -out oe_license.txt -d; fi
  - if [ "$TRAVIS_SECURE_ENV_VARS" == false ]; then echo "OpenEye license will not be installed in forks."; fi


install:

  - |
    if [ $ENVIRON == "RDKIT"]; then
      conda env create -n test python=$PYTHON_VER -f devtools/conda-envs/rdkit-2018.yaml
    elif [ $ENVIRON == "OPENEYE"]; then
      conda env create -n test python=$PYTHON_VER -f devtools/conda-envs/openeye-2018.yaml
    elif [ $ENVIRON == "CMILES"]; then
      conda env create -n test python=$PYTHON_VER -f devtools/conda-envs/cmiles.yaml
    else
      echo "ERROR: No match for ENVIRON ($ENVIRON)
      exit 1
    fi

  - conda activate test

  - python setupt.py develop --no-deps

before_script:
  - sleep 5
  - python -V
  - conda list

script:
  - pytest --cov=cmiles cmiles/tests/

notifications:
    email: false

after_success:
  - codecov
